# Generated by Django 5.0.2 on 2024-05-20 23:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentHelp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')], default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('likes', models.IntegerField(default=0)),
                ('caption', models.CharField(max_length=10000, null=True, verbose_name='Caption')),
                ('is_transport', models.BooleanField(default=False)),
                ('is_Recommandation', models.BooleanField(default=False)),
                ('is_Logement', models.BooleanField(default=False)),
                ('is_Stage', models.BooleanField(default=False)),
                ('is_EvenSocial', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvenClub',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('intitulé_ev', models.CharField(max_length=100)),
                ('description_ev', models.CharField(max_length=500)),
                ('lieu_ev', models.CharField(max_length=100)),
                ('contactInfo_ev', models.CharField(max_length=8)),
                ('club_ev', models.CharField(default='Default Club Name', max_length=50)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='EvenSocial',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('intitulé_es', models.CharField(max_length=100)),
                ('description_es', models.CharField(max_length=500)),
                ('lieu_es', models.CharField(max_length=100)),
                ('contactInfo_es', models.CharField(max_length=8)),
                ('prix_es', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('localisation', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('contactInfo', models.CharField(max_length=8)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('texte', models.CharField(max_length=100)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('typeStg', models.IntegerField(choices=[(1, 'Ouvrier'), (2, 'Technicien'), (3, 'PFE')], default=1)),
                ('société', models.CharField(max_length=50)),
                ('durée', models.IntegerField()),
                ('sujet', models.CharField(max_length=100)),
                ('contactInfo', models.CharField(max_length=8)),
                ('spécialité', models.CharField(max_length=50)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('départ', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('heure_dep', models.TimeField(default=datetime.datetime.now)),
                ('nbre_sièges', models.IntegerField()),
                ('contactInfo', models.CharField(max_length=8)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='StudentHelp.poste')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='StudentHelp.poste')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='profile_pciture')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
