# Generated by Django 5.0.2 on 2024-05-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='is_EvenClub',
            field=models.BooleanField(default=False),
        ),
    ]
